version: "3.9"

services:
  api:
    build: .
    container_name: api_gastos
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - gastos-net

networks:
  gastos-net:
    external: true